apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: agents
      port: 50000
      protocol: TCP
  selector:
    app: jenkins