apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: web-application
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./web-application
  prune: true
  sourceRef:
    kind: GitRepository
    name: web-application
  validation: client