apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: artifact-manager
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./artifact-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: artifact-manager
  validation: client